### ISSUE TITLE
issue with installing cocotbext-wishbone

### ISSUE THREAD

**Issue by OesterKweker** [wallento/cocomod-wishbone#14]
Hi,

:tools>python3 -m pip install cocotbext-wishbone
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement cocotbext-wishbone (from versions: none)
ERROR: No matching distribution found for cocotbext-wishbone

any idea how to resolve this error message?
I also tried this

```

> tools>python3 -m pip install -e cocotbext-wishbone
> Defaulting to user installation because normal site-packages is not writeable
> Obtaining file:///tools/cocotbext-wishbone
> ERROR: Command errored out with exit status 1:
> command: /opt/rh/rh-python36/root/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tools/cocotbext-wishbone/setup.py'"'"'; file='"'"'/tools/cocotbext-wishbone/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-g90qfibg
> cwd: /tools/cocotbext-wishbone/
> Complete output (7 lines):
> Traceback (most recent call last):
> File "", line 1, in
> File "/tools/cocotbext-wishbone/setup.py", line 4, in
> long_description = fh.read()
> File "/opt/rh/rh-python36/root/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
> return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1370: ordinal not in range(128)
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by cmarqu** [comment]
See #15 and #16 :)

**Comment by Martoni** [comment]
Solved by downloading a new pip version https://github.com/wallento/cocotbext-wishbone/issues/22
