### ISSUE TITLE
Version via pip (0.2) too old for cocotb >= 1.6

### ISSUE THREAD

**Issue by tmeissner** [wallento/cocomod-wishbone#22]
The version of this package on pip (0.2) seems to be too old to work with cocotb >= 1.6. The needed fix is already done in the git repo (#18), but not pushed to the package index, I assume.

```
...
/usr/local/lib/python3.9/dist-packages/attrdict/mapping.py:4: DeprecationWarning: Using or importing the ABCs from 'coll
ections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
/usr/local/lib/python3.9/dist-packages/attrdict/mixins.py:5: DeprecationWarning: Using or importing the ABCs from 'colle
ctions' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping, MutableMapping, Sequence
     0.00ns CRITICAL Failed to import module tb_wishbone: No module named 'cocotb.drivers'
     0.00ns INFO     MODULE variable was "tb_wishbone"
     0.00ns INFO     Traceback: 
     0.00ns INFO     Traceback (most recent call last):
                       File "/usr/local/lib/python3.9/dist-packages/cocotb/regression.py", line 175, in _discover_tests
                         module = _my_import(module_name)
                       File "/usr/local/lib/python3.9/dist-packages/cocotb/regression.py", line 69, in _my_import
                         mod = __import__(name)
                       File "/build/tests/tb_wishbone.py", line 11, in <module>
                         from cocotbext.wishbone.monitor import WishboneSlave
                       File "/usr/local/lib/python3.9/dist-packages/cocotbext/wishbone/__init__.py", line 1, in <module>
                         from .driver import *
                       File "/usr/local/lib/python3.9/dist-packages/cocotbext/wishbone/driver.py", line 6, in <module>
                         from cocotb.drivers import BusDriver
                     ModuleNotFoundError: No module named 'cocotb.drivers'
                     
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/cocotb/__init__.py", line 242, in _initialise_testbench
    _initialise_testbench_(argv_)
  File "/usr/local/lib/python3.9/dist-packages/cocotb/__init__.py", line 345, in _initialise_testbench_
    regression_manager = RegressionManager.from_discovery(top)
  File "/usr/local/lib/python3.9/dist-packages/cocotb/regression.py", line 150, in from_discovery
    return cls(dut, tests)
  File "/usr/local/lib/python3.9/dist-packages/cocotb/regression.py", line 129, in __init__
    for test in tests:
  File "/usr/local/lib/python3.9/dist-packages/cocotb/regression.py", line 175, in _discover_tests
    module = _my_import(module_name)
  File "/usr/local/lib/python3.9/dist-packages/cocotb/regression.py", line 69, in _my_import
    mod = __import__(name)
  File "/build/tests/tb_wishbone.py", line 11, in <module>
    from cocotbext.wishbone.monitor import WishboneSlave
  File "/usr/local/lib/python3.9/dist-packages/cocotbext/wishbone/__init__.py", line 1, in <module>
    from .driver import *
  File "/usr/local/lib/python3.9/dist-packages/cocotbext/wishbone/driver.py", line 6, in <module>
    from cocotb.drivers import BusDriver
ModuleNotFoundError: No module named 'cocotb.drivers'
     0.00ns ERROR    Failing test at simulator request before test run completion: Simulator shutdown prematurely
```

**Comment by Martoni** [comment]
@wallento can you give us admin right on pypi.org or release new version of the package ?

Thanks

**Comment by Martoni** [comment]
@tmeissner I downloaded a new version (0.2.2).
Is it ok now ?

**Comment by tmeissner** [comment]
LGTM, my tests now work with the package installed by pip. Thanks.
